name: Test

on:
  push:
    branches: [master, main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - run: echo $HOME
      - run: bundle binstubs jekyll --path=$HOME/.local/bin

      - run : cat $HOME/.local/bin/jekyll

#      - run: ls -lA /opt/hostedtoolcache/Ruby/2.6.6/x64/bin
#      - run: gem update --system
#      - run: tree $GITHUB_WORKSPACE/vendor/bundle/ruby/
#      - run: echo "$GITHUB_WORKSPACE/vendor/bundle/ruby/2.6.0/bin" >> $GITHUB_PATH

      - run: echo $PATH

      - run: jekyll -v
