name: Test

on:
  push:
    branches: [master, main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - run: tree $GITHUB_WORKSPACE/vendor/bundle/ruby/

      - name: Add bundle to PATH
        run: echo "$GITHUB_WORKSPACE/vendor/bundle/ruby/2.7.0/bin" >> $GITHUB_PATH

      - run: echo $PATH

      - run: jekyll -v
